FROM python:3.10

# ENV CHROMA_DB_IMPL=clickhouse
# ENV CLICKHOUSE_HOST=clickhouse
# ENV CLICKHOUSE_PORT=8123
# ENV ALLOW_EMPTY_PASSWORD=yes
# ENV CLICKHOUSE_TCP_PORT=9000

# ENV CLICKHOUSE_HTTP_PORT=8123

WORKDIR /chroma

COPY ./requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./bin/docker_entrypoint.sh /docker_entrypoint.sh
COPY ./ /chroma

EXPOSE 8000

CMD ["/docker_entrypoint.sh"]
